global:
  scrape_interval:     5s # By default, scrape targets every 15 seconds.

  # external_labels:
  #  monitor: 'codelab-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  # Example job for node_exporter
  - job_name: 'node_exporter'
    static_configs:
      - targets: ['node-exporter:9100']  # can give ['localhost:9100','192.162.3.162:9100'] if you want to scrap from multiple instance

  # Example job for cadvisor
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

