apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-express
  namespace: wanderlust
  labels:
    app: mongo-express
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo-express
  template:
    metadata:
      labels:
        app: mongo-express
    spec:
      containers:
      - name: mongo-express
        image: mongo-express:latest
        ports:
        - containerPort: 8081
        env:
        - name: ME_CONFIG_MONGODB_ADMINUSERNAME
          valueFrom:
            secretKeyRef:
              name: wanderlust-secret
              key: username
        - name: ME_CONFIG_MONGODB_ADMINPASSWORD
          valueFrom:
            secretKeyRef:
              name: wanderlust-secret
              key: password
        - name: ME_CONFIG_MONGODB_URL 
          valueFrom:
            configMapKeyRef:
              name: wanderlust-config
              key: database_url
---
apiVersion: v1
kind: Service
metadata:
  name: mongo-express
  namespace: wanderlust
spec:
  type: ClusterIP
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app: mongo-express
